### ISSUE TITLE
Sound issue

### ISSUE THREAD

**Issue by arminn** [xen-troops/android_manifest#58]
Android 11 for prod-devel has an ION memory issue related to media playback.

Should be fixed by:
https://github.com/xen-troops/android_device_xenvm/pull/57
https://github.com/xen-troops/linux/pull/105

**Comment by arminn** [comment]
To reproduce: 

stagefright -a /system/product/media/audio/ringtones/Oberon.ogg 

this command should provide some progress with size of processes file

**Comment by rshym** [comment]
System sounds and audio playback plays without any issues.
Tested on Kingfisher H3.
